default: &global
  adapter: sqlite3
  encoding: unicode
  pool: 5

development:
  <<: *global
  database: ivr-rails_development

test:
  <<: *global
  database: ivr-rails_test

production: &production
  <<: *global
  database: ivr-rails_production
  username: ivr-rails
  password: <%= ENV['IVR-RAILS_DATABASE_PASSWORD'] %>
